import Head from 'next/head'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

import NavBar from './components/navBar'
import Footer from './components/footer'
import Hero from './components/home-layout/hero'
import Featured from './components/home-layout/featured'
import Auctions from './components/home-layout/auctions'
import Creator from './components/home-layout/creator'
import Newsletter from './components/home-layout/newsletter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Artsy </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <NavBar />
        <Hero />
        <Featured />
        <Auctions />
        <Creator />
        <Newsletter />
        <Footer />
      </main>
    </>
  )
}
